name: System Info Workflow

on: [push]

jobs:
  system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current date
        run: date

      - name: Show current working directory
        run: pwd

      - name: List files in the repo
        run: ls -la
